# Generated by Django 5.2.2 on 2025-06-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(blank=True, to='films.actor'),
        ),
    ]
