# Generated by Django 5.2.2 on 2025-06-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
