# Generated by Django 5.2.2 on 2025-06-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_actor_actor_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.RemoveField(
            model_name='film',
            name='release_date',
        ),
    ]
