# Generated by Django 5.2.2 on 2025-06-16 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_remove_film_actors_remove_film_director_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='films.film')),
            ],
            options={
                'verbose_name': 'FilmComment',
                'verbose_name_plural': 'FilmComments',
            },
        ),
        migrations.CreateModel(
            name='FilmMoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_trailer_url', models.URLField()),
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
            options={
                'verbose_name': 'FilmMoreInfo',
                'verbose_name_plural': 'FilmMoreInfos',
            },
        ),
    ]
