# Generated by Django 5.2.2 on 2025-06-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_filmcomment_filmmoreinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmoreinfo',
            name='youtube_trailer_url',
            field=models.URLField(max_length=500),
        ),
    ]
