# Generated by Django 5.2.2 on 2025-06-18 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_filmcomment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='film',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='member',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='film',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='member',
        ),
        migrations.AlterField(
            model_name='filmcomment',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
