# Generated by Django 5.2.2 on 2025-06-18 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_alter_film_genre_remove_rating_film_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OscarAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oscars', to='films.actor')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
            options={
                'verbose_name': 'Oscar Award',
                'verbose_name_plural': 'Oscar Awards',
            },
        ),
    ]
