# Generated by Django 5.2.2 on 2025-06-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_oscaraward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='films',
        ),
        migrations.AddField(
            model_name='actor',
            name='films',
            field=models.TextField(blank=True, null=True),
        ),
    ]
