# Generated by Django 5.2.2 on 2025-06-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_alter_oscaraward_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oscaraward',
            name='actor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
