# Generated by Django 5.2.2 on 2025-06-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_alter_oscaraward_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='films',
        ),
    ]
