# Generated by Django 5.2.2 on 2025-06-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_remove_actor_biography_remove_actor_films'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='birthday',
        ),
    ]
