# Generated by Django 5.2.2 on 2025-06-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_remove_actor_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oscaraward',
            name='category',
        ),
    ]
