# Generated by Django 5.2.2 on 2025-06-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_remove_login_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='created_at',
        ),
    ]
