# Generated by Django 5.2.2 on 2025-06-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0020_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='sifre',
            field=models.CharField(default=int, max_length=100),
            preserve_default=False,
        ),
    ]
