# Generated by Django 5.2.2 on 2025-06-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0021_register_sifre'),
    ]

    operations = [
        migrations.CreateModel(
            name='oneCıkanFilmler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.TextField(max_length=100)),
                ('youtube_url', models.URLField()),
            ],
            options={
                'verbose_name': 'OneCıkanFilm',
                'verbose_name_plural': 'OneCıkanFilmler',
            },
        ),
    ]
