# Generated by Django 5.2.2 on 2025-07-08 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0022_onecıkanfilmler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cinsiyet', models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], default='Erkek', max_length=10)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.register')),
            ],
            options={
                'verbose_name': 'Üye',
                'verbose_name_plural': 'Üyeler',
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.members'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
