# Generated by Django 5.2.2 on 2025-07-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0023_members_alter_review_member_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
