# Generated by Django 5.2.2 on 2025-07-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0024_alter_members_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciYorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=100)),
                ('yorum_metni', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
